### ISSUE TITLE
Change timeout when use --sockets

### ISSUE THREAD

**Issue by disaster37** [magnusbaeck/logstash-filter-verifier#32]
I have lot of rules and logstash take some time to start. So I get timeout when use --sockets.
There are a way to change this timeout ?

**Comment by breml** [comment]
Currently there is no option/flag to modify the timeout. This constant is used https://github.com/magnusbaeck/logstash-filter-verifier/blob/master/logstash-filter-verifier.go#L122.
But it would not be that much a problem to add a flag for this timeout.

That being said, it really surprises me, that the 60 seconds timeout does not work for you, because my observation is, that Logstash normally needs ~15 seconds to start. The actual processing of the testcases normally only takes very little time (except you use very slow filters in Logstash like lookups to other systems).
Could you provide some more details about your use case and how may testcases you are talking about?

**Comment by matejzero** [comment]
In my case, logstash takes close to 1m to start (running time logstash-filter-verifier reports a little under 60s).

I do have a lot of patterns and configuration files.

**Comment by breml** [comment]
Created PR #33 to resolve this issue.

**Comment by disaster37** [comment]
Thanks a lot ;)

**Comment by matejzero** [comment]
Thanks Breml, you are the best:)
