### ISSUE TITLE
Logstash 6.x compatibility

### ISSUE THREAD

**Issue by breml** [magnusbaeck/logstash-filter-verifier#43]
For Logstash 6.x there is a breaking change [announced](https://www.elastic.co/blog/logstash-lines-2017-05-16), which makes the flags `-e` and `-f` mutually exclusive (see https://github.com/elastic/logstash/issues/6926 and https://github.com/elastic/logstash/pull/6976/files). LFV at the moment uses the current behavior (concatenation of `-e` and `-f`) to add the necessary `input` and `output` to the filter "under test" (see https://github.com/magnusbaeck/logstash-filter-verifier/blob/master/logstash/process.go#L77-L83 and https://github.com/magnusbaeck/logstash-filter-verifier/blob/master/logstash/parallel_process.go#L183-L189). This needs to be changed in order to become compatible with Logstash 6.x.

**Comment by magnusbaeck** [comment]
This should just be a matter of generating a file in the config file tempdir with the correct `-e` argument as its contents, which is backwards compatible.

**Comment by Etharin** [comment]
Hi Magnus, can you explain a bit more what's needed to generate the file? Or is this a code change that's needed to support 6 now it's released?

**Comment by magnusbaeck** [comment]
A (simple) code change is required.

**Comment by Etharin** [comment]
Cool, will continue to use Logstash 5 for now. Thanks.

**Comment by jstoja** [comment]
Hey @magnusbaeck any news on the status of this issue?

**Comment by NetAppBlueDevil** [comment]
Upvote on this as well now that 6.0 is GA from elastic

**Comment by magnusbaeck** [comment]
Most of what's needed is available from the master branch and you're welcome to try it out. AFAIK the following things are still outstanding:

* The logstash.yml from the Logstash distribution is used instead of a clean copy.
* The same data directory as the installed Logstash is used, resulting in Logstash refusing to start if the lock file is present.
* Generate a pipeline configuration file containing the stuff we currently pass via the `-e` option.

The first item is just lacking a few tests, the second is quite trivial, and the third shouldn't take long either. I think I'll be able to wrap things up the coming weekend.

**Comment by magnusbaeck** [comment]
Pushed a few more commits now and the only remaining issue is the last bullet from the list above. I think I have working code but tests remain to be written.
